"use client";
import "./connectors.css";
import {usePathname,useRouter} from "next/navigation";
import {useState} from "react";
import {Pulse,ArrowRight,ArrowUpRight,Brain,ChartLineUp,Check,CheckCircle,Clock,CloudCheck,Funnel,Heartbeat,Lightning,MagnifyingGlass,Path,ShieldCheck,Sparkle,TrendUp,Warning,Waveform} from "@phosphor-icons/react";

const nav=[{label:"Overview",path:"/",icon:Pulse},{label:"Measurement health",path:"/measurement-health",icon:Heartbeat},{label:"Channel performance",path:"/channel-performance",icon:ChartLineUp},{label:"Multi-touch attribution",path:"/multi-touch-attribution",icon:Path},{label:"Agent recommendations",path:"/recommendations",icon:Brain}];
const channels=[{name:"Google Ads",spend:"$82.4k",pipeline:"$316k",roas:"3.8×",change:"+12%",color:"blue"},{name:"LinkedIn",spend:"$47.8k",pipeline:"$244k",roas:"5.1×",change:"+24%",color:"cyan"},{name:"Meta",spend:"$38.2k",pipeline:"$91k",roas:"2.4×",change:"−8%",color:"violet"},{name:"Organic",spend:"—",pipeline:"$182k",roas:"—",change:"+17%",color:"green"}];
const connectors=["Google Ads","Meta Ads","LinkedIn","GA4","Salesforce","BigQuery"];

function Header(){const apiConnectors=[{name:"Google Ads",mark:"G",tone:"google"},{name:"Facebook Ads",mark:"f",tone:"facebook"},{name:"LinkedIn Ads",mark:"in",tone:"linkedin"},{name:"Salesforce",mark:"SF",tone:"salesforce"}];return <header className="top"><div className="search"><MagnifyingGlass/><input placeholder="Ask about spend, pipeline, or measurement health"/></div><div className="header-connectors" aria-label="Connected marketing APIs">{apiConnectors.map(api=><button key={api.name} title={`${api.name} API connected`} aria-label={`${api.name} API connected`}><span className={api.tone}>{api.mark}</span><i/></button>)}</div><div className="sync"><span/><strong>Data synced</strong><small>6 min ago</small></div><button className="run"><Lightning weight="fill"/>Run audit</button></header>}
function Metric({label,value,note,tone="good"}:{label:string,value:string,note:string,tone?:string}){return <article className="metric"><span>{label}</span><strong>{value}</strong><small className={tone}>{note}</small></article>}

function Overview(){return <><div className="heading"><div><p className="kicker"><Sparkle weight="fill"/>MARKETING MEASUREMENT INTELLIGENCE</p><h1>Know what&apos;s working.<br/><em>Trust why.</em></h1><p>Stitch connects campaign activity to qualified pipeline, audits the measurement, and tells your team what deserves attention.</p></div><div className="confidence"><ShieldCheck/><span><small>Measurement confidence</small><strong>87%</strong></span></div></div><section className="metrics"><Metric label="Marketing spend" value="$184.6k" note="↑ 6.4% vs last month"/><Metric label="Qualified pipeline" value="$833k" note="↑ 18.2% vs last month"/><Metric label="Revenue influenced" value="$412k" note="↑ 11.7% vs last month"/><Metric label="Blended ROAS" value="4.5×" note="0.6× above target"/></section><section className="overview-grid"><article className="card narrative"><div className="card-title"><div><span className="agent-dot"/><h2>Agent briefing</h2></div><small>Updated 6 minutes ago</small></div><h3>Pipeline grew faster than spend, but <em>Google Ads conversions may be overstated.</em></h3><p>LinkedIn produced 2.4× more qualified pipeline per lead than Google Ads. Meanwhile, 18% of Google Ads conversions have no matching Salesforce record.</p><div className="brief-actions"><button>Review evidence <ArrowRight/></button><button>Open recommendations <ArrowUpRight/></button></div></article><article className="card channel-mini"><div className="card-title"><h2>Channel contribution</h2><span>Pipeline</span></div>{channels.map(c=><div className="channel-row" key={c.name}><i className={c.color}/><span>{c.name}</span><b>{c.pipeline}</b><small className={c.change.startsWith("+")?"good":"bad"}>{c.change}</small></div>)}</article></section><section className="connectors">{connectors.map((c,i)=><button key={c}><CloudCheck weight="fill"/><span><strong>{c}</strong><small>{i===5?"Warehouse":"Connected"}</small></span><i/></button>)}</section></>}

function Health(){const issues=[{sev:"critical",title:"Google Ads conversions missing CRM matches",detail:"184 conversions have no corresponding Salesforce lead.",impact:"Potential overstatement: 18%",action:"Investigate"},{sev:"warning",title:"UTM campaign values are fragmented",detail:"Seven naming variants map to “Q3 Enterprise”.",impact:"$42k spend affected",action:"Review mapping"},{sev:"warning",title:"LinkedIn click IDs expire before CRM sync",detail:"Offline conversion upload is delayed by 9 days.",impact:"31 opportunities affected",action:"View fix"},{sev:"healthy",title:"GA4 revenue matches warehouse totals",detail:"Variance remains within the accepted 2% threshold.",impact:"Validated 6 min ago",action:"View evidence"}];return <><div className="heading compact"><div><p className="kicker"><Heartbeat weight="fill"/>MEASUREMENT HEALTH</p><h1>Find the breaks before<br/><em>they become decisions.</em></h1><p>Stitch continuously audits tracking, joins, definitions, and platform totals.</p></div><div className="health-score"><strong>87</strong><span>Health score<small>+4 this week</small></span></div></div><section className="health-layout"><div className="issue-list">{issues.map(x=><article className="card issue" key={x.title}><span className={`severity ${x.sev}`}><Warning weight="fill"/></span><div><span className={`tag ${x.sev}`}>{x.sev}</span><h2>{x.title}</h2><p>{x.detail}</p><small>{x.impact}</small></div><button>{x.action}<ArrowRight/></button></article>)}</div><aside className="card coverage"><div className="card-title"><h2>Tracking coverage</h2><span>Last 30 days</span></div>{[["Campaign UTMs",94],["Click IDs",81],["CRM matches",82],["Revenue joins",98],["Channel taxonomy",91]].map(([n,v])=><div className="coverage-row" key={n as string}><div><span>{n}</span><b>{v}%</b></div><i><em style={{width:`${v}%`}}/></i></div>)}</aside></section></>}

function Channels(){return <><div className="heading compact"><div><p className="kicker"><ChartLineUp weight="fill"/>CHANNEL PERFORMANCE</p><h1>Compare contribution,<br/><em>not just clicks.</em></h1><p>Evaluate every channel using spend, qualified pipeline, revenue, and confidence.</p></div><button className="date"><Clock/>Last 30 days</button></div><section className="metrics"><Metric label="Cost per opportunity" value="$2,418" note="↓ 9.2% improvement"/><Metric label="Pipeline per $1" value="$4.51" note="↑ $0.43 this month"/><Metric label="Win rate" value="28.6%" note="↑ 3.1 percentage points"/><Metric label="Avg. sales cycle" value="41 days" note="↓ 5 days faster"/></section><article className="card table-card"><div className="card-title"><h2>Channel performance</h2><button><Funnel/>Filter</button></div><div className="table"><div className="tr head"><span>Channel</span><span>Spend</span><span>Qualified pipeline</span><span>ROAS</span><span>Trend</span></div>{channels.map(c=><div className="tr" key={c.name}><span><i className={c.color}/><b>{c.name}</b></span><span>{c.spend}</span><span>{c.pipeline}</span><span>{c.roas}</span><span className={c.change.startsWith("+")?"good":"bad"}>{c.change}</span></div>)}</div></article></>}

function Attribution(){const [model,setModel]=useState("Data-driven");const touches=[{day:"Day 1",channel:"LinkedIn",event:"Sponsored post click",detail:"Enterprise security guide",credit:"18%",color:"cyan"},{day:"Day 4",channel:"Organic",event:"Returned via search",detail:"Viewed integrations page",credit:"12%",color:"green"},{day:"Day 9",channel:"Google Ads",event:"High-intent search",detail:"Visited pricing twice",credit:"24%",color:"blue"},{day:"Day 14",channel:"Email",event:"Customer story opened",detail:"Forwarded internally",credit:"16%",color:"orange"},{day:"Day 21",channel:"Sales",event:"Opportunity created",detail:"$84k enterprise plan",credit:"30%",color:"violet"}];return <><div className="heading compact"><div><p className="kicker"><Path weight="fill"/>MULTI-TOUCH ATTRIBUTION</p><h1>See every influence on<br/><em>the path to revenue.</em></h1><p>Explore how channels work together across the full customer journey.</p></div><div className="model-switch">{["First touch","Linear","Data-driven"].map(x=><button className={model===x?"active":""} onClick={()=>setModel(x)} key={x}>{x}</button>)}</div></div><section className="attribution-summary"><article className="card account"><span className="logo">NL</span><div><small>SELECTED JOURNEY</small><h2>Northstar Labs</h2><p>Enterprise opportunity · $84,000</p></div><span className="won"><CheckCircle weight="fill"/>Qualified</span></article><Metric label="Journey length" value="21 days" note="5 meaningful touches"/><Metric label="Channels involved" value="4" note="LinkedIn initiated journey"/><Metric label="Confidence" value="92%" note="Identity resolved"/></section><article className="card journey"><div className="card-title"><div><h2>Customer journey</h2><span>{model} attribution model</span></div><small>Jan 8 — Jan 29</small></div><div className="journey-line">{touches.map((t,i)=><div className="touch" key={t.day}><div className="touch-top"><span>{t.day}</span><b>{t.credit}</b></div><i className={t.color}>{i+1}</i><div className="touch-card"><span>{t.channel}</span><strong>{t.event}</strong><small>{t.detail}</small></div></div>)}</div></article><section className="attribute-grid"><article className="card"><div className="card-title"><h2>Revenue credit by channel</h2><span>{model}</span></div><div className="credit-bars">{[["Sales",30,"violet"],["Google Ads",24,"blue"],["LinkedIn",18,"cyan"],["Email",16,"orange"],["Organic",12,"green"]].map(([n,v,c])=><div key={n as string}><span>{n}</span><i><b className={c as string} style={{width:`${Number(v)*2.8}%`}}/></i><strong>{v}%</strong></div>)}</div></article><article className="card journey-insight"><Sparkle weight="fill"/><p>LinkedIn created awareness, but Google Ads captured existing intent. Removing either touch would likely reduce conversion probability.</p><button>Ask the agent about this journey <ArrowRight/></button></article></section></>}

function Recommendations(){const [done,setDone]=useState<number[]>([]);const items=[{title:"Fix Google Ads offline conversion matching",why:"18% of reported conversions have no CRM record.",impact:"High",gain:"Restore reporting confidence"},{title:"Shift 12% of Meta prospecting budget to LinkedIn",why:"LinkedIn produces 2.4× more qualified pipeline per lead.",impact:"High",gain:"+$38k projected pipeline"},{title:"Standardize Q3 Enterprise campaign taxonomy",why:"Seven naming variants fragment performance reporting.",impact:"Medium",gain:"Unify $42k of spend"}];return <><div className="heading compact"><div><p className="kicker"><Brain weight="fill"/>AGENT RECOMMENDATIONS</p><h1>Clear actions, backed by<br/><em>visible evidence.</em></h1><p>Every recommendation includes its reasoning, expected impact, and confidence.</p></div><span className="ready"><span/>3 ready for review</span></div><section className="rec-list">{items.map((x,i)=><article className="card rec" key={x.title}><span className="rec-num">0{i+1}</span><div className="rec-body"><div><span className={`impact ${x.impact.toLowerCase()}`}>{x.impact} impact</span><small>88% confidence</small></div><h2>{x.title}</h2><p><Sparkle weight="fill"/>{x.why}</p><strong><TrendUp/>Expected outcome · {x.gain}</strong></div><div className="rec-buttons">{done.includes(i)?<span className="complete"><CheckCircle weight="fill"/>Approved</span>:<><button>Dismiss</button><button onClick={()=>setDone([...done,i])}><Check/>Approve</button></>}</div></article>)}</section></>}

export default function App(){const router=useRouter();const pathname=usePathname();const active=nav.find(x=>x.path===pathname)?.label||"Overview";return <main><aside><div className="brand"><span><Waveform weight="bold"/></span><div><strong>Stitch</strong><small>Measurement agent</small></div></div><nav><p>WORKSPACE</p>{nav.map(x=>{const Icon=x.icon;return <button className={active===x.label?"active":""} onClick={()=>router.push(x.path)} key={x.label}><Icon/>{x.label}{x.label==="Measurement health"&&<i>3</i>}</button>})}</nav><div className="agent-status"><div><span/><strong>Agent monitoring</strong></div><p>6 sources · 24 checks running</p></div><p className="creator">Created by <strong>Jacob Chen</strong></p></aside><section className="workspace"><Header/><div className="content">{active==="Overview"&&<Overview/>}{active==="Measurement health"&&<Health/>}{active==="Channel performance"&&<Channels/>}{active==="Multi-touch attribution"&&<Attribution/>}{active==="Agent recommendations"&&<Recommendations/>}</div></section></main>}

